<?php

namespace Database\Seeders;

use App\Modules\Admin\Models\ChatbotKnowledge;
use Illuminate\Database\Seeder;

class ChatbotKnowledgeSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'language' => 'en',
                'intent' => 'website_overview',
                'title' => 'Website Overview',
                'summary' => 'Movaflex Task Manager includes Dashboard, Projects, Tasks, Kanban, Calendar, Notifications, Email Alerts, Reports, and role pages.',
                'steps' => null,
                'keywords' => ['website', 'overview', 'modules', 'menu', 'navigation', 'content'],
                'links' => [
                    ['label' => 'Dashboard', 'path' => '/dashboard'],
                    ['label' => 'Projects', 'path' => '/projects'],
                    ['label' => 'Tasks', 'path' => '/tasks'],
                    ['label' => 'Kanban', 'path' => '/tasks/kanban'],
                    ['label' => 'Calendar', 'path' => '/tasks/calendar'],
                    ['label' => 'Notifications', 'path' => '/notifications/history'],
                    ['label' => 'Email Alerts', 'path' => '/email'],
                    ['label' => 'Reports', 'path' => '/reports'],
                ],
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'language' => 'en',
                'intent' => 'create_task',
                'title' => 'Create Task (Step by Step)',
                'summary' => 'You can create a task from the Task page or Dashboard.',
                'steps' => [
                    'Open Tasks, then click Create Task.',
                    'Select project and enter task title.',
                    'Set status, priority, and due date.',
                    'Add assignees and task details.',
                    'Click Save/Create and verify in list or Kanban.',
                ],
                'keywords' => ['create task', 'new task', 'task step', 'task guide'],
                'links' => [
                    ['label' => 'Create Task', 'path' => '/tasks/create'],
                    ['label' => 'Task List', 'path' => '/tasks'],
                ],
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'language' => 'en',
                'intent' => 'create_project',
                'title' => 'Create Project (Step by Step)',
                'summary' => 'Project setup is available for authorized users.',
                'steps' => [
                    'Open Projects, then click Create Project.',
                    'Enter project name and description.',
                    'Set project status and schedule fields.',
                    'Assign owners/members if needed.',
                    'Save and verify project appears in list.',
                ],
                'keywords' => ['create project', 'new project', 'project step', 'project guide'],
                'links' => [
                    ['label' => 'Projects', 'path' => '/projects'],
                    ['label' => 'Create Project', 'path' => '/projects/create'],
                ],
                'is_active' => true,
                'sort_order' => 30,
            ],
            [
                'language' => 'en',
                'intent' => 'status_flow',
                'title' => 'Task Status Flow',
                'summary' => 'Standard flow: Not Started (todo) -> On Going (in_progress) -> For Review -> Done. Overdue means due date passed while not done.',
                'steps' => [
                    'Start at NOT STARTED (todo).',
                    'Move to ON GOING (in_progress) when work begins.',
                    'Move to FOR REVIEW after completing output.',
                    'Approve to DONE after validation.',
                    'If due date is passed and not done, it is OVERDUE.',
                ],
                'keywords' => ['status', 'workflow', 'not started', 'ongoing', 'for review', 'done', 'overdue'],
                'links' => [
                    ['label' => 'Task Board', 'path' => '/tasks'],
                    ['label' => 'Kanban', 'path' => '/tasks/kanban'],
                ],
                'is_active' => true,
                'sort_order' => 40,
            ],
            [
                'language' => 'en',
                'intent' => 'email_alerts',
                'title' => 'Email Alerts and Recipients',
                'summary' => 'Email Alerts page shows warning/critical/reminder/overdue levels and recipient preview (From, To, CC, BCC).',
                'steps' => [
                    'Open Email Alert page.',
                    'Review Mail Header Preview.',
                    'Check warning/critical/reminder/overdue sections.',
                    'Use test email actions if needed.',
                ],
                'keywords' => ['email', 'alerts', 'bcc', 'cc', 'mail header', 'deadline'],
                'links' => [
                    ['label' => 'Email Alerts', 'path' => '/email'],
                    ['label' => 'Admin Configuration', 'path' => '/admin/configuration'],
                ],
                'is_active' => true,
                'sort_order' => 50,
            ],
            [
                'language' => 'en',
                'intent' => 'full_website_flow',
                'title' => 'End-to-End Website Flow',
                'summary' => 'Overall website flow: login -> main task layout -> centralized task encoding -> status movement -> completed checklist -> calendar views -> notifications and email alerts -> reports.',
                'steps' => [
                    'Login and open Main Task Layout (Kanban with Backlogs, To-do, In-Progress, Done).',
                    'Encode task data in centralized tracker (project, task no, process, priority, owner, PIC, dates, links).',
                    'Track status changes and movement across columns automatically.',
                    'When status is done, task moves to Checklist/Completed and actual completion date is recorded.',
                    'Use Company Calendar split views: Event Calendar and Tasks Calendar (active tasks only).',
                    'Use Notifications and Email Alerts for reminder, urgent, and overdue escalation.',
                    'Review dashboards and reports for KPI and governance checks.',
                ],
                'keywords' => ['full flow', 'website flow', 'end to end', 'system flow', 'demo flow', 'workflow', 'process flow'],
                'links' => [
                    ['label' => 'Main Layout (Kanban)', 'path' => '/tasks/kanban'],
                    ['label' => 'Centralized Tracker', 'path' => '/tasks'],
                    ['label' => 'Create Task', 'path' => '/tasks/create'],
                    ['label' => 'Company Calendar', 'path' => '/tasks/calendar'],
                    ['label' => 'Notifications', 'path' => '/notifications/history'],
                    ['label' => 'Email Alerts', 'path' => '/email'],
                    ['label' => 'Reports', 'path' => '/reports'],
                ],
                'is_active' => true,
                'sort_order' => 60,
            ],
            [
                'language' => 'en',
                'intent' => 'centralized_task_tracker',
                'title' => 'Centralized Task Tracker Guide',
                'summary' => 'Centralized tracker stores all mandatory task details and supports automatic deadline and workflow updates.',
                'steps' => [
                    'Open Tasks/Create Task.',
                    'Complete mandatory fields: Project, Task Process, Specific Process, Company, PIC, Date Received, Date Started, Assignee.',
                    'Task No is auto-generated and SLA days are applied from process mapping.',
                    'Due date can be auto-computed from Date Started plus SLA.',
                    'Save and confirm in active list and Kanban.',
                ],
                'keywords' => ['centralized tracker', 'task tracker', 'mandatory fields', 'sla', 'specific process', 'task no', 'encode task'],
                'links' => [
                    ['label' => 'Task List', 'path' => '/tasks'],
                    ['label' => 'Create Task', 'path' => '/tasks/create'],
                ],
                'is_active' => true,
                'sort_order' => 70,
            ],
            [
                'language' => 'en',
                'intent' => 'role_based_access',
                'title' => 'Role-Based Access and Responsibilities',
                'summary' => 'Each role sees only relevant modules and actions to keep governance controlled and auditable.',
                'steps' => [
                    'Admin: full system control and configuration.',
                    'Manager/Project Manager: oversee workload, review progress, and monitor delivery risks.',
                    'Lead: quality gate for review and task completion validation.',
                    'Member/Employee: execute assigned tasks and update status accurately.',
                ],
                'keywords' => ['roles', 'access', 'permissions', 'admin', 'manager', 'project manager', 'lead', 'member'],
                'links' => [
                    ['label' => 'Dashboard', 'path' => '/dashboard'],
                    ['label' => 'Task Board', 'path' => '/tasks'],
                ],
                'is_active' => true,
                'sort_order' => 80,
            ],
            [
                'language' => 'en',
                'intent' => 'calendar_split_flow',
                'title' => 'Company Calendar Split Flow',
                'summary' => 'Company Calendar has two parts: Event Calendar for meetings/events and Tasks Calendar for active task deadlines.',
                'steps' => [
                    'Open Company Calendar page.',
                    'Use Event Calendar panel for meetings and holidays overview.',
                    'Use Tasks Calendar panel to view active task deadlines only.',
                    'Event data is encoded through dedicated modules, not directly in the calendar grid.',
                ],
                'keywords' => ['calendar', 'event calendar', 'tasks calendar', 'meeting', 'holiday', 'deadline calendar'],
                'links' => [
                    ['label' => 'Company Calendar', 'path' => '/tasks/calendar'],
                    ['label' => 'Meetings', 'path' => '/meetings'],
                    ['label' => 'Holidays', 'path' => '/holidays'],
                ],
                'is_active' => true,
                'sort_order' => 90,
            ],
            [
                'language' => 'fil',
                'intent' => 'website_overview',
                'title' => 'Buod ng Website',
                'summary' => 'Ang Movaflex Task Manager ay may Dashboard, Projects, Tasks, Kanban, Calendar, Notifications, Email Alerts, Reports, at role pages.',
                'steps' => null,
                'keywords' => ['website', 'buod', 'modules', 'menu', 'navigation', 'nilalaman'],
                'links' => [
                    ['label' => 'Dashboard', 'path' => '/dashboard'],
                    ['label' => 'Projects', 'path' => '/projects'],
                    ['label' => 'Tasks', 'path' => '/tasks'],
                    ['label' => 'Kanban', 'path' => '/tasks/kanban'],
                    ['label' => 'Calendar', 'path' => '/tasks/calendar'],
                    ['label' => 'Notifications', 'path' => '/notifications/history'],
                    ['label' => 'Email Alerts', 'path' => '/email'],
                    ['label' => 'Reports', 'path' => '/reports'],
                ],
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'language' => 'fil',
                'intent' => 'create_task',
                'title' => 'Pag-create ng Task (Step by Step)',
                'summary' => 'Maaaring gumawa ng task mula sa Task page o Dashboard.',
                'steps' => [
                    'Buksan ang Tasks at i-click ang Create Task.',
                    'Piliin ang project at ilagay ang task title.',
                    'I-set ang status, priority, at due date.',
                    'Magdagdag ng assignees at task details.',
                    'I-save at i-check sa list o Kanban.',
                ],
                'keywords' => ['gawa task', 'create task', 'new task', 'task step', 'paano task'],
                'links' => [
                    ['label' => 'Create Task', 'path' => '/tasks/create'],
                    ['label' => 'Task List', 'path' => '/tasks'],
                ],
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'language' => 'fil',
                'intent' => 'create_project',
                'title' => 'Pag-create ng Project (Step by Step)',
                'summary' => 'Available ang project setup para sa authorized users.',
                'steps' => [
                    'Buksan ang Projects at i-click ang Create Project.',
                    'Ilagay ang project name at description.',
                    'I-set ang status at schedule.',
                    'Mag-assign ng owner/members kung kailangan.',
                    'I-save at i-check sa project list.',
                ],
                'keywords' => ['gawa project', 'create project', 'new project', 'project step', 'paano project'],
                'links' => [
                    ['label' => 'Projects', 'path' => '/projects'],
                    ['label' => 'Create Project', 'path' => '/projects/create'],
                ],
                'is_active' => true,
                'sort_order' => 30,
            ],
            [
                'language' => 'fil',
                'intent' => 'status_flow',
                'title' => 'Daloy ng Task Status',
                'summary' => 'Karaniwang daloy: Not Started (todo) -> On Going (in_progress) -> For Review -> Done. Overdue kapag lampas due date at hindi pa done.',
                'steps' => [
                    'Magsimula sa NOT STARTED (todo).',
                    'Lipat sa ON GOING (in_progress) kapag sinimulan.',
                    'Lipat sa FOR REVIEW kapag tapos na ang output.',
                    'I-approve sa DONE pagkatapos ng validation.',
                    'Kapag lampas due date at hindi done, OVERDUE ito.',
                ],
                'keywords' => ['status', 'workflow', 'not started', 'on going', 'for review', 'done', 'overdue'],
                'links' => [
                    ['label' => 'Task Board', 'path' => '/tasks'],
                    ['label' => 'Kanban', 'path' => '/tasks/kanban'],
                ],
                'is_active' => true,
                'sort_order' => 40,
            ],
            [
                'language' => 'fil',
                'intent' => 'email_alerts',
                'title' => 'Email Alerts at Recipients',
                'summary' => 'Ipinapakita ng Email Alerts page ang warning/critical/reminder/overdue at Mail Header Preview (From, To, CC, BCC).',
                'steps' => [
                    'Buksan ang Email Alert page.',
                    'I-review ang Mail Header Preview.',
                    'Tingnan ang warning/critical/reminder/overdue sections.',
                    'Gamitin ang test email actions kung kailangan.',
                ],
                'keywords' => ['email', 'alerts', 'bcc', 'cc', 'mail header', 'deadline'],
                'links' => [
                    ['label' => 'Email Alerts', 'path' => '/email'],
                    ['label' => 'Admin Configuration', 'path' => '/admin/configuration'],
                ],
                'is_active' => true,
                'sort_order' => 50,
            ],
            [
                'language' => 'fil',
                'intent' => 'full_website_flow',
                'title' => 'Buong Daloy ng Website',
                'summary' => 'Kabuuang daloy: login -> main task layout -> centralized encoding -> automatic status movement -> completed checklist -> calendar views -> notifications/email alerts -> reports.',
                'steps' => [
                    'Mag-login at buksan ang Main Task Layout (Backlogs, To-do, In-Progress, Done).',
                    'Mag-encode ng task sa centralized tracker gamit ang kumpletong fields.',
                    'I-update ang status at automatic lilipat ang task sa tamang column.',
                    'Kapag done, mapupunta sa Checklist/Completed at may actual completion date.',
                    'Gamitin ang Company Calendar split view para sa events at active task deadlines.',
                    'I-check ang notifications at email alerts para sa reminder, urgent, at overdue.',
                    'Suriin ang dashboard at reports para sa KPI at governance.',
                ],
                'keywords' => ['buong flow', 'daloy ng website', 'end to end', 'system flow', 'demo flow', 'workflow'],
                'links' => [
                    ['label' => 'Main Layout (Kanban)', 'path' => '/tasks/kanban'],
                    ['label' => 'Centralized Tracker', 'path' => '/tasks'],
                    ['label' => 'Create Task', 'path' => '/tasks/create'],
                    ['label' => 'Company Calendar', 'path' => '/tasks/calendar'],
                    ['label' => 'Notifications', 'path' => '/notifications/history'],
                    ['label' => 'Email Alerts', 'path' => '/email'],
                    ['label' => 'Reports', 'path' => '/reports'],
                ],
                'is_active' => true,
                'sort_order' => 60,
            ],
            [
                'language' => 'fil',
                'intent' => 'centralized_task_tracker',
                'title' => 'Guide sa Centralized Task Tracker',
                'summary' => 'Nasa centralized tracker ang lahat ng mandatory task details at automated deadline logic.',
                'steps' => [
                    'Buksan ang Tasks/Create Task.',
                    'Kumpletuhin ang mandatory fields: Project, Task Process, Specific Process, Company, PIC, Date Received, Date Started, Assignee.',
                    'Auto-generated ang Task No at SLA base sa process mapping.',
                    'Pwedeng auto-compute ang due date mula Date Started plus SLA.',
                    'I-save at i-verify sa active list at Kanban.',
                ],
                'keywords' => ['centralized tracker', 'task tracker', 'mandatory fields', 'sla', 'specific process', 'task no', 'encode task'],
                'links' => [
                    ['label' => 'Task List', 'path' => '/tasks'],
                    ['label' => 'Create Task', 'path' => '/tasks/create'],
                ],
                'is_active' => true,
                'sort_order' => 70,
            ],
            [
                'language' => 'fil',
                'intent' => 'role_based_access',
                'title' => 'Role-Based Access at Responsibilidad',
                'summary' => 'Bawat role ay may tamang scope lang para controlled at auditable ang proseso.',
                'steps' => [
                    'Admin: full control at configuration.',
                    'Manager/Project Manager: oversight sa workload at delivery risk.',
                    'Lead: quality gate para sa review at completion validation.',
                    'Member/Employee: execution ng assigned tasks at tamang status updates.',
                ],
                'keywords' => ['roles', 'access', 'permissions', 'admin', 'manager', 'project manager', 'lead', 'member'],
                'links' => [
                    ['label' => 'Dashboard', 'path' => '/dashboard'],
                    ['label' => 'Task Board', 'path' => '/tasks'],
                ],
                'is_active' => true,
                'sort_order' => 80,
            ],
            [
                'language' => 'fil',
                'intent' => 'calendar_split_flow',
                'title' => 'Daloy ng Company Calendar (2 Parts)',
                'summary' => 'May dalawang bahagi ang calendar: Event Calendar at Tasks Calendar para sa active deadlines.',
                'steps' => [
                    'Buksan ang Company Calendar page.',
                    'Gamitin ang Event Calendar para sa meetings at holidays.',
                    'Gamitin ang Tasks Calendar para sa active task deadlines lamang.',
                    'Ang event inputs ay encoded sa dedicated modules, hindi diretso sa calendar grid.',
                ],
                'keywords' => ['calendar', 'event calendar', 'tasks calendar', 'meeting', 'holiday', 'deadline calendar'],
                'links' => [
                    ['label' => 'Company Calendar', 'path' => '/tasks/calendar'],
                    ['label' => 'Meetings', 'path' => '/meetings'],
                    ['label' => 'Holidays', 'path' => '/holidays'],
                ],
                'is_active' => true,
                'sort_order' => 90,
            ],
            [
                'language' => 'en',
                'intent' => 'projects_module_guide',
                'title' => 'Projects Module Guide',
                'summary' => 'Projects module is used to create projects, assign members, and set ownership before task execution starts.',
                'steps' => [
                    'Open Projects and create or select a project.',
                    'Set project details and owner.',
                    'Assign members based on role and scope.',
                    'Use the project as source for task encoding and reporting.',
                ],
                'keywords' => ['projects module', 'project page', 'project flow', 'project members', 'project owner'],
                'links' => [
                    ['label' => 'Projects', 'path' => '/projects'],
                    ['label' => 'Create Project', 'path' => '/projects/create'],
                ],
                'is_active' => true,
                'sort_order' => 100,
            ],
            [
                'language' => 'en',
                'intent' => 'tasks_module_guide',
                'title' => 'Tasks Module Guide',
                'summary' => 'Tasks module is the centralized tracker for encoding, filtering, and managing active and completed tasks.',
                'steps' => [
                    'Open Task list to see active and completed tabs.',
                    'Filter by status, assignee, priority, date, and company.',
                    'Open Create Task to encode complete mandatory details.',
                    'Use row actions to open task details and updates.',
                ],
                'keywords' => ['tasks module', 'task list', 'centralized tracker', 'task tab', 'done tasks'],
                'links' => [
                    ['label' => 'Task List', 'path' => '/tasks'],
                    ['label' => 'Create Task', 'path' => '/tasks/create'],
                ],
                'is_active' => true,
                'sort_order' => 110,
            ],
            [
                'language' => 'en',
                'intent' => 'kanban_module_guide',
                'title' => 'Kanban Main Layout Guide',
                'summary' => 'Kanban is the main layout after login, with four columns: Backlogs, To-do, In-Progress, and Done.',
                'steps' => [
                    'Open Kanban main layout.',
                    'Review cards by project, task no, due date, priority, owner, and PIC.',
                    'Move status to update workflow and column placement.',
                    'Use this board for daily execution standup.',
                ],
                'keywords' => ['kanban', 'main layout', 'backlogs', 'to-do', 'in-progress', 'done board'],
                'links' => [
                    ['label' => 'Main Layout (Kanban)', 'path' => '/tasks/kanban'],
                    ['label' => 'Task List', 'path' => '/tasks'],
                ],
                'is_active' => true,
                'sort_order' => 120,
            ],
            [
                'language' => 'en',
                'intent' => 'notifications_module_guide',
                'title' => 'Notifications and Email Alerts Guide',
                'summary' => 'Notifications provide in-app updates while email alerts escalate warning, urgent, and overdue task deadlines.',
                'steps' => [
                    'Check in-app notifications for assignment and status updates.',
                    'Open Email Alerts to monitor reminder levels and recipients.',
                    'Use standard email templates for reminder, urgent, and overdue.',
                    'Track response and follow-up for overdue actions.',
                ],
                'keywords' => ['notifications module', 'email alerts', 'reminder', 'urgent', 'overdue', 'recipient'],
                'links' => [
                    ['label' => 'Notifications', 'path' => '/notifications/history'],
                    ['label' => 'Email Alerts', 'path' => '/email'],
                ],
                'is_active' => true,
                'sort_order' => 130,
            ],
            [
                'language' => 'en',
                'intent' => 'reports_module_guide',
                'title' => 'Reports Module Guide',
                'summary' => 'Reports module supports KPI monitoring and export for leadership review.',
                'steps' => [
                    'Open Reports page.',
                    'Review status trends and delivery performance.',
                    'Export CSV/PDF for weekly and monthly governance meetings.',
                ],
                'keywords' => ['reports module', 'kpi report', 'csv export', 'pdf export', 'trend analysis'],
                'links' => [
                    ['label' => 'Reports', 'path' => '/reports'],
                    ['label' => 'Dashboard', 'path' => '/dashboard'],
                ],
                'is_active' => true,
                'sort_order' => 140,
            ],
            [
                'language' => 'en',
                'intent' => 'demo_walkthrough_script',
                'title' => 'Demo Walkthrough Script',
                'summary' => 'Recommended sequence for presenting the system smoothly from login to reports.',
                'steps' => [
                    'Login and open Kanban main layout.',
                    'Create a task with process and specific process.',
                    'Show automatic due date and task number behavior.',
                    'Move status to Done and show completed checklist tab.',
                    'Open split calendar and explain event vs task views.',
                    'Show notification and email alert templates.',
                    'Close with dashboard KPI and reports export.',
                ],
                'keywords' => ['demo script', 'walkthrough', 'presentation flow', 'how to demo', 'demo guide'],
                'links' => [
                    ['label' => 'Main Layout (Kanban)', 'path' => '/tasks/kanban'],
                    ['label' => 'Create Task', 'path' => '/tasks/create'],
                    ['label' => 'Company Calendar', 'path' => '/tasks/calendar'],
                    ['label' => 'Email Alerts', 'path' => '/email'],
                    ['label' => 'Reports', 'path' => '/reports'],
                ],
                'is_active' => true,
                'sort_order' => 150,
            ],
            [
                'language' => 'fil',
                'intent' => 'projects_module_guide',
                'title' => 'Guide sa Projects Module',
                'summary' => 'Dito ginagawa ang project setup, members, at ownership bago ang task execution.',
                'steps' => [
                    'Buksan ang Projects at gumawa o pumili ng project.',
                    'I-set ang project details at owner.',
                    'I-assign ang members ayon sa role at scope.',
                    'Gamitin ang project bilang source sa task encoding at reports.',
                ],
                'keywords' => ['projects module', 'project page', 'project flow', 'project members', 'project owner'],
                'links' => [
                    ['label' => 'Projects', 'path' => '/projects'],
                    ['label' => 'Create Project', 'path' => '/projects/create'],
                ],
                'is_active' => true,
                'sort_order' => 100,
            ],
            [
                'language' => 'fil',
                'intent' => 'tasks_module_guide',
                'title' => 'Guide sa Tasks Module',
                'summary' => 'Ang Tasks module ang centralized tracker para sa active at completed tasks.',
                'steps' => [
                    'Buksan ang Task list para makita ang active at completed tabs.',
                    'Gumamit ng filters gaya ng status, assignee, priority, date, at company.',
                    'Buksan ang Create Task para sa complete mandatory encoding.',
                    'Gamitin ang actions para buksan at i-update ang task details.',
                ],
                'keywords' => ['tasks module', 'task list', 'centralized tracker', 'task tab', 'done tasks'],
                'links' => [
                    ['label' => 'Task List', 'path' => '/tasks'],
                    ['label' => 'Create Task', 'path' => '/tasks/create'],
                ],
                'is_active' => true,
                'sort_order' => 110,
            ],
            [
                'language' => 'fil',
                'intent' => 'kanban_module_guide',
                'title' => 'Guide sa Kanban Main Layout',
                'summary' => 'Ang Kanban ang main layout pagkatapos mag-login, may apat na columns: Backlogs, To-do, In-Progress, Done.',
                'steps' => [
                    'Buksan ang Kanban main layout.',
                    'Suriin ang cards ayon sa project, task no, due date, priority, owner, at PIC.',
                    'I-update ang status para lumipat sa tamang column.',
                    'Gamitin ito sa daily execution standup.',
                ],
                'keywords' => ['kanban', 'main layout', 'backlogs', 'to-do', 'in-progress', 'done board'],
                'links' => [
                    ['label' => 'Main Layout (Kanban)', 'path' => '/tasks/kanban'],
                    ['label' => 'Task List', 'path' => '/tasks'],
                ],
                'is_active' => true,
                'sort_order' => 120,
            ],
            [
                'language' => 'fil',
                'intent' => 'notifications_module_guide',
                'title' => 'Guide sa Notifications at Email Alerts',
                'summary' => 'Ang notifications ay para sa in-app updates, habang ang email alerts ay para sa escalation ng warning, urgent, at overdue.',
                'steps' => [
                    'I-check ang in-app notifications para sa assignment at status updates.',
                    'Buksan ang Email Alerts para sa reminder levels at recipients.',
                    'Gamitin ang standardized templates para sa reminder, urgent, at overdue.',
                    'I-monitor ang response at follow-up para sa overdue tasks.',
                ],
                'keywords' => ['notifications module', 'email alerts', 'reminder', 'urgent', 'overdue', 'recipient'],
                'links' => [
                    ['label' => 'Notifications', 'path' => '/notifications/history'],
                    ['label' => 'Email Alerts', 'path' => '/email'],
                ],
                'is_active' => true,
                'sort_order' => 130,
            ],
            [
                'language' => 'fil',
                'intent' => 'reports_module_guide',
                'title' => 'Guide sa Reports Module',
                'summary' => 'Ang Reports module ay para sa KPI monitoring at export ng leadership reports.',
                'steps' => [
                    'Buksan ang Reports page.',
                    'Suriin ang status trends at delivery performance.',
                    'Mag-export ng CSV/PDF para sa weekly at monthly governance meetings.',
                ],
                'keywords' => ['reports module', 'kpi report', 'csv export', 'pdf export', 'trend analysis'],
                'links' => [
                    ['label' => 'Reports', 'path' => '/reports'],
                    ['label' => 'Dashboard', 'path' => '/dashboard'],
                ],
                'is_active' => true,
                'sort_order' => 140,
            ],
            [
                'language' => 'fil',
                'intent' => 'demo_walkthrough_script',
                'title' => 'Demo Walkthrough Script',
                'summary' => 'Recommended sequence para sa smooth system demo mula login hanggang reports.',
                'steps' => [
                    'Mag-login at buksan ang Kanban main layout.',
                    'Gumawa ng task gamit ang process at specific process.',
                    'Ipakita ang automatic due date at task number behavior.',
                    'I-move ang status to Done at ipakita ang checklist/completed tab.',
                    'Buksan ang split calendar at ipaliwanag ang event vs task views.',
                    'Ipakita ang notification at email alert templates.',
                    'Tapusin sa dashboard KPI at reports export.',
                ],
                'keywords' => ['demo script', 'walkthrough', 'presentation flow', 'how to demo', 'demo guide'],
                'links' => [
                    ['label' => 'Main Layout (Kanban)', 'path' => '/tasks/kanban'],
                    ['label' => 'Create Task', 'path' => '/tasks/create'],
                    ['label' => 'Company Calendar', 'path' => '/tasks/calendar'],
                    ['label' => 'Email Alerts', 'path' => '/email'],
                    ['label' => 'Reports', 'path' => '/reports'],
                ],
                'is_active' => true,
                'sort_order' => 150,
            ],
            [
                'language' => 'en',
                'intent' => 'panel_defense_qa',
                'title' => 'Panel Defense Q&A (Quick Answers)',
                'summary' => 'Use these short answers for common panel questions during demo.',
                'steps' => [
                    'Q: What problem does this system solve? A: It centralizes task governance and improves deadline visibility and accountability.',
                    'Q: How is deadline control enforced? A: Due date logic + SLA mapping + overdue tracking + escalation alerts.',
                    'Q: Why role-based access? A: It limits actions per responsibility and improves auditability and compliance.',
                    'Q: What is automated? A: Task number generation, deadline computation, status movement views, done timestamp, and alert triggers.',
                    'Q: How do you monitor performance? A: KPI dashboard, pending/overdue counters, and exportable reports.',
                ],
                'keywords' => ['panel question', 'defense', 'q and a', 'qa', 'demo questions', 'common questions'],
                'links' => [
                    ['label' => 'Dashboard', 'path' => '/dashboard'],
                    ['label' => 'Main Layout (Kanban)', 'path' => '/tasks/kanban'],
                    ['label' => 'Reports', 'path' => '/reports'],
                ],
                'is_active' => true,
                'sort_order' => 160,
            ],
            [
                'language' => 'fil',
                'intent' => 'panel_defense_qa',
                'title' => 'Panel Defense Q&A (Mabilisang Sagot)',
                'summary' => 'Mga maiikling sagot para sa karaniwang tanong ng panel sa demo.',
                'steps' => [
                    'Q: Anong problem ang sinosolve ng system? A: Centralized task governance para sa visibility, accountability, at control.',
                    'Q: Paano na-co-control ang deadlines? A: Due date logic, SLA mapping, overdue tracking, at escalation alerts.',
                    'Q: Bakit role-based access? A: Para malinaw ang scope per role at mas auditable ang actions.',
                    'Q: Ano ang automated dito? A: Task number, deadline computation, status movement views, done timestamp, at alert triggers.',
                    'Q: Paano mino-monitor ang performance? A: KPI dashboard, pending/overdue counters, at exportable reports.',
                ],
                'keywords' => ['panel question', 'defense', 'q and a', 'qa', 'demo questions', 'common questions', 'tanong panel'],
                'links' => [
                    ['label' => 'Dashboard', 'path' => '/dashboard'],
                    ['label' => 'Main Layout (Kanban)', 'path' => '/tasks/kanban'],
                    ['label' => 'Reports', 'path' => '/reports'],
                ],
                'is_active' => true,
                'sort_order' => 160,
            ],
        ];

        foreach ($rows as $row) {
            ChatbotKnowledge::query()->updateOrCreate(
                [
                    'language' => $row['language'],
                    'intent' => $row['intent'],
                ],
                $row,
            );
        }
    }
}
